srcdir=..

CXXFILES = DataTransferProtocolSender.cpp \
	DirectoryIterator.cpp \
	FileSystem.cpp \
	FileSystemImpl.cpp \
	FileSystemKey.cpp \
	Hdfs.cpp \
	InputStream.cpp \
	InputStreamImpl.cpp \
	KerberosName.cpp \
	LeaseRenewer.cpp \
	LocalBlockReader.cpp \
	OutputStream.cpp \
	OutputStreamImpl.cpp \
	Packet.cpp \
	PacketHeader.cpp \
	PacketPool.cpp \
	PeerCache.cpp \
	Permission.cpp \
	Pipeline.cpp \
	ReadShortCircuitInfo.cpp \
	RemoteBlockReader.cpp \
	Token.cpp \
	UserInfo.cpp

OBJS = $(CXXFILES:.cpp=.o)

include ../src.mk


