srcdir=..

CXXFILES = CFileWrapper.cpp \
	Exception.cpp \
	ExceptionInternal.cpp \
	Hash.cpp \
	HWCrc32c.cpp \
	Logger.cpp \
	MappedFileWrapper.cpp \
	SessionConfig.cpp \
	StackPrinter.cpp \
	SWCrc32c.cpp \
	Thread.cpp \
	WritableUtils.cpp \
	WriteBuffer.cpp \
	XmlConfig.cpp

OBJS = $(CXXFILES:.cpp=.o)

include ../src.mk

