srcdir=..

CXXFILES = RpcAuth.cpp \
	RpcChannel.cpp \
	RpcChannelKey.cpp \
	RpcClient.cpp \
	RpcConfig.cpp \
	RpcContentWrapper.cpp \
	RpcProtocolInfo.cpp \
	RpcRemoteCall.cpp \
	RpcServerInfo.cpp \
	SaslClient.cpp

OBJS = $(CXXFILES:.cpp=.o)

include ../src.mk

